# Generated by Django 5.1.3 on 2025-01-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='pyment_method',
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'Stripe'), (2, 'Paypal')], null=True),
        ),
    ]
