# Generated by Django 5.1.5 on 2025-02-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_update_at_transaction_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'سترايب'), (2, 'بايبال')], null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(0, 'قيد الانتظار'), (1, 'مكتمل')], default=0),
        ),
    ]
