# Generated by Django 5.1.4 on 2024-12-10 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='order',
        ),
    ]
