# Generated by Django 5.1.4 on 2024-12-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0002_remove_author_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
