# Generated by Django 5.1.4 on 2024-12-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0004_alter_author_name_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='Product',
            new_name='product',
        ),
    ]
