# Generated by Django 5.1.3 on 2025-02-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0009_remove_order_customer_remove_order_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
